@startuml appointment
title Appointment Class Diagram

left to right direction

class Appointment {
    pk : uuid
    title : str
    start_at : datetime
    end_at : datetime
}

class UserAppointment {
    pk : uuid
    appointment_pk : uuid
    user_pk : uuid
}

User "1" -- "0..*" UserAppointment : user_pk
Appointment "1" -- "0..*"  UserAppointment: appointment_pk

@endumld