@startuml Utilisateur
title User Diagram

left to right direction

class User {
    pk : uuid
    role : enum
    username : str
    first_name : str
    last_name : str
    password_hash : str
    email : str
}

class Student {}

class Tutor {}

User <|-- Student
User <|-- Tutor

@enduml