site_name: Specifications

# theme:
#         name: material
#         language: fr
#         palette:
#                 - scheme: default
#                   primary: indigo
#                   accent: blue
#                   toggle:
#                           icon: material/weather-night
#                           name: Passer en mode sombre
#                 - scheme: slate
#                   primary: indigo
#                   accent: blue
#                   toggle:
#                           icon: material/weather-sunny
#                           name: Passer en mode clair
#         features:
#                 - navigation.tabs
#                 - navigation.sections
#                 - navigation.expand
#                 - navigation.top
#                 - toc.integrate
#                 - content.code.copy

nav:
        - Accueil: index.md
        - Acteurs: actors.md
        - Spécifications fonctionnelles:
                  - Compte Utilisateur: features/authentication.md
                  - Communication: features/communication.md
                  - Rendez-vous: features/appointment.md
                  - Tâches: features/tasks.md
        - Spécifications techniques: project_specifications.md
        - Diagrammes de classes: class_diagrams.md
        - MVP: mvp.md
