@startuml task_management
title Gestion des Tâches

!include /specifications/docs/diagrams/actors/common.puml

student --|> Utilisateur
tutor --|> Utilisateur

usecase "Consulter mes tâches" as see_owned_tasks
usecase "Consulter les tâches assignées" as see_student_assigned_tasks
usecase "Modifier une tâche assignée" as update_student_assigned_task
usecase "Modifier ma tâche" as update_task
usecase "Compléter ma tâche" as complete_task

Utilisateur -- see_owned_tasks
Utilisateur -- complete_task
Utilisateur -- update_task

tutor -- see_student_assigned_tasks
tutor -- update_student_assigned_task

@enduml

