@startuml authentication
title Authentification

actor "Visiteur" as visitor
!include /specifications/docs/diagrams/actors/common.puml

student --|> user
tutor --|> user

usecase "S'inscrire" as register
usecase "Se connecter" as login
usecase "Se déconnecter" as logout
usecase "Réinitialiser mot de passe" as reset_password

visitor -- register
user -- login
user -- logout
user -- reset_password

@endumld