

@startuml message
title Message

!include /specifications/docs/diagrams/actors/common.puml

usecase "Envoyer message" as send_message
usecase "Lire message" as read_message
usecase "Marqué lu" as set_read_message
usecase "Envoyer notification par email" as send_email_notification

student --|> user
tutor --|> user

user -- send_message
user -- read_message

send_message ..> send_email_notification
read_message ..> set_read_message

@enduml