

@startuml message
title Message

!include /specifications/docs/diagrams/actors/common.puml

usecase "Envoyer message" as send_message
usecase "Lire message" as read_message

student --|> user
tutor --|> user

user -- send_message
user -- read_message

@enduml