

@startuml message
title Message

!include /specifications/docs/diagrams/actors/common.puml

usecase "Envoyer un message" as send_message
usecase "Consulter mes messages" as see_messages
usecase "Lire un message" as read_message
usecase "Marquer lu" as set_read_message
usecase "Envoyer une notification par email" as send_email_notification

student --|> user
tutor --|> user

user -- send_message
user -- read_message
user -- see_messages

send_message ..> send_email_notification
read_message ..> set_read_message

@enduml