

@startuml pined_message
title Messages épinglés

!include /specifications/docs/diagrams/actors/actors.puml

usecase "Epingler message" as pin_message
usecase "Chercher messages épinglés" as research_pined_message

student --|> user
tutor --|> user

user -- pin_message
user -- research_pined_message

@enduml