@startuml authentication
title Authentification

!include /specifications/docs/diagrams/actors/actors.puml

student --|> user
tutor --|> user

usecase "S'inscrire" as register
usecase "Se connecter" as login
usecase "Se déconnecter" as logout

user -- register
user -- login
user -- logout

@endumld