@startuml authentication
title Authentification

actor "Visiteur" as visitor
!include /specifications/docs/diagrams/actors/common.puml

student --|> Utilisateur
tutor --|> Utilisateur

usecase "M'inscrire" as register
usecase "Me connecter \n à mon espace personnel " as login
usecase "Me déconnecter \n de mon espace personnel" as logout
usecase "Réinitialiser \n mon mot de passe" as reset_password

visitor -- register
Utilisateur -- login
Utilisateur -- logout
Utilisateur -- reset_password

@endumld