@startuml data_management
title Gestion données personnelles

!include /specifications/docs/diagrams/actors/common.puml

student --|> Utilisateur
tutor --|> Utilisateur

usecase "Modifier mon mot de passe" as password_managing
usecase "Modifier mes données personnelles" as personal_data_managing

Utilisateur -- password_managing
Utilisateur -- personal_data_managing

@endumld