@startuml appointment
title Rendez-vous

!include /specifications/docs/diagrams/actors/common.puml

usecase "Planifier un rendez-vous" as plan_appointment
usecase "Modifier un rendez-vous" as update_appointment
usecase "Consulter ses rendez-vous" as see_appointments
usecase "Consulter le détail d'un rendez-vous" as see_appointment

tutor -- plan_appointment
tutor -- update_appointment
tutor -- see_appointments
tutor -- see_appointment


student -- see_appointments
student -- see_appointment

@enduml