

@startuml pinned_message
title Messages épinglés

!include /specifications/docs/diagrams/actors/common.puml

usecase "Epingler un message" as pin_message
usecase "Désépingler un message" as upnin_message
usecase "Consulter mes messages épinglés" as research_pinned_message

student --|> Utilisateur
tutor --|> Utilisateur

Utilisateur -- pin_message
Utilisateur -- upnin_message
Utilisateur -- research_pinned_message

@enduml