@startuml actors
title Acteurs


actor "Visiteur" as visitor

!include /specifications/docs/diagrams/actors/common.puml

actor "Utilisateur" as user


student --|> user
tutor --|> user

@enduml